### ISSUE TITLE
`(.write js/process.stderr)` crashes repl

### ISSUE THREAD

**Issue by pesterhazy** [anmonteiro/lumo#125]
Lumo exits when I type `(.write js/process.stderr)`:

```
Lumo 1.2.0
ClojureScript 1.9.482
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (.write js/process.stderr)
nil
readline.js:982
            throw err;
            ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:658:11)
    at g ([eval]:2:18687)
    at y ([eval]:2:19320)
    at Interface.<anonymous> ([eval]:2:20873)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:189:7)
    at Interface._onLine (readline.js:238:10)
    at Interface._line (readline.js:582:8)
    at Interface._ttyWrite (readline.js:861:14)
    at ReadStream.onkeypress (readline.js:117:10)
```

I know I'm missing the first argument to the method, but the exception should be caught inside the REPL.

**Comment by anmonteiro** [comment]
this doesn't happen in master
