### ISSUE TITLE
Quick start build failing with very unclear error

### ISSUE THREAD

**Issue by benbotwin** [anmonteiro/lumo#329]
I'm trying to follow the quick start build guide for clojurescript but with the lumo build library instead.
My `src/hello_world/core.cljs` is identical to the one found on the quick start guide and my `build.cljs` is identical to what is in the README

When running `lumo -c src ./build.cljs` I keep getting this error

```
failed compiling file:out/cljs/core.cljs
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 (evalmachine.<anonymous>:609:25)
	 Function.lumo.compiler.compile_file.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:616:4)
	 (Object.lumo$closure$compile_file)
	 (evalmachine.<anonymous>:1625:21)
	 (Object.lumo$closure$_compile)
	 (Object.lumo$closure$compile_from_jar)
	 (evalmachine.<anonymous>:1660:21)
	 (Object.lumo$closure$_compile)

should never happen!
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:1922:449)
	 (Object.lumo$io$slurp)
	 (Object.lumo$compiler$emit_cached_core)
	 (evalmachine.<anonymous>:482:28)
	 Function.lumo.compiler.with_core_cljs.cljs$core$IFn$_invoke$arity$2 (evalmachine.<anonymous>:231:85)
	 Function.lumo.compiler.compile_file_STAR_.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:461:41)
	 (evalmachine.<anonymous>:586:41)
	 Function.lumo.compiler.compile_file.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:616:4)
```

**Comment by anmonteiro** [comment]
This is most likely fixed in master. What version of Lumo?

**Comment by benbotwin** [comment]
I'm using the version from brew. It's 1.7.0

**Comment by anmonteiro** [comment]
Try using `brew install --devel lumo` for 1.8-beta and report back please

**Comment by benbotwin** [comment]
It compiles now with both `brew install --HEAD lumo` and `brew install --devel lumo` but I get an error when running `node out/main.js`

```
/Users/benbot/Documents/dev/projects/alien/out/main.js:1
(function (exports, require, module, __filename, __dirname) { goog.addDependency("base.js", ['goog'], []);
                                                              ^

ReferenceError: goog is not defined
    at Object.<anonymous> (/Users/benbot/Documents/dev/projects/alien/out/main.js:1:63)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by anmonteiro** [comment]
I'm going to close this issue as there's not enough information. If you're still seeing this in Lumo 1.9.0-alpha, please provide necessary steps to repro, including a minimal project (1 file should be able to repro the issue) and a build file.
