### ISSUE TITLE
Lumo fails resolving :foreign-libs modules

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#392]
I tried the setup in this [ClojureScript vanilla test](https://github.com/clojure/clojurescript/blob/v1.10/src/test/clojure/cljs/build_api_tests.clj#L229).

The compiler options are:

```
{:main 'speed-of-light.core
 :output-to "out/speed_of_light.js"
 :output-dir "out"
 :optimizations :none
 :verbose true
 :foreign-libs [{:module-type :es6
                 :file "js/es6_dep.js"
                 :provides ["es6_calc"]}
                {:module-type :es6
                 :file "js/es6_default_hello.js"
                 :provides ["es6_default_hello"]}]
 :closure-warnings {:check-types :off}}
```

The files are in place, basically `js/es6_dep.js` is importing `calculator.js` but there is an error:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Can't resolve './calculator' in '/home/arichiardi/git/lumo-repros'
    at onError (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/arichiardi/git/lumo-repros/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/arichiardi/git/lumo-repros/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
```

**Comment by arichiardi** [comment]
This is a non-issue, the path within the cljs test to `calculator` is wrong. Closing.

**Comment by arichiardi** [comment]
Just for posterity, this was actually fixed with https://github.com/anmonteiro/lumo/commit/d0dfa58767eba5773f1013b2af29225d6d3f227e

It now throws but is handled correctly and compilation finishes:

```
Options passed to ClojureScript compiler: {:output-dir "out", :closure-warnings {:check-types :off, :check-variables :off}, :closure-defines {}, :ups-libs nil, :cache-analysis true, :closure-module-roots [], :optimizations :none, :ups-foreign-libs [], :verbose true, :aot-cache false, :preloads [process.env], :ignore-js-module-exts [".css"], :output-to "out/speed_of_light.js", :preamble ["cljs/imul.js"], :ups-externs nil, :opts-cache "cljsc_opts.edn", :source-map true, :foreign-libs [{:module-type :es6, :file "js/es6_dep.js", :provides ["es6_calc"]} {:module-type :es6, :file "js/es6_default_hello.js", :provides ["es6_default_hello"]}], :cache-analysis-format :transit, :main 'speed-of-light.core, :emit-constants nil}
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Can't resolve './calculator' in '/home/arichiardi/git/lumo-repros'
    at onError (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/arichiardi/git/lumo-repros/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/arichiardi/git/lumo-repros/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/home/arichiardi/git/lumo-repros/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)

WARNING: #js {:file /home/arichiardi/git/lumo-repros/js/es6_dep.js, :description Failed to load module "./calculator", :type JSC_JS_MODULE_LOAD_WARNING, :lineNo 1, :charNo 0}
WARNING: #js {:file /home/arichiardi/git/lumo-repros/js/es6_dep.js, :description Failed to load module "./calculator", :type JSC_JS_MODULE_LOAD_WARNING, :lineNo 1, :charNo 30}
```
