### ISSUE TITLE
Lumo crashes on official clojure alpine docker image

### ISSUE THREAD

**Issue by vikeri** [anmonteiro/lumo#415]
Based on [clojure:lein-2.8.1-alpine](https://hub.docker.com/r/library/clojure/tags/lein-2.8.1-alpine/)

Running: `apk add --update nodejs && npm install -g lumo-cljs@1.8.0` works

Then `lumo` fails with the following error.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/lumo-cljs/bin/lumo ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by anmonteiro** [comment]
this is unfortunate, and I'm aware of it. The root cause of this issue is that Alpine doesn't include `glibc` (it uses `musl` instead) and Lumo is not currently compiled against `musl`

**Comment by vikeri** [comment]
Ok, I solved it by going up to non-alpine: https://hub.docker.com/r/vikeri/clojure-node

**Comment by anmonteiro** [comment]
@vikeri there's also a Lumo image at https://hub.docker.com/r/anmonteiro/lumo/

**Comment by vikeri** [comment]
@anmonteiro Nice! I can recommend the automated github build flow, then the docker file and corresponding github project show up in dockerhub as well. And you don't have to manually push to dockerhub :)
