### ISSUE TITLE
No such file or directory, lstat $HOME/target - version 1.10

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#468]
Hi Antonio, first of all thanks for updating `lumo`!

I have downloaded the latest linux executable and I wanted to report a problem:

```
$ lumo
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/home/arichiardi/target'
    at Object.realpathSync (fs.js:1476:7)
    at toRealPath (internal/modules/cjs/loader.js:256:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:325:24)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:652:25)
    at Function.resolve (internal/modules/cjs/helpers.js:19:19)
    at /home/arichiardi/bin/lumo:313:42
    at Object.<anonymous> (/home/arichiardi/bin/lumo:315:7)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at _third_party_main.js:38:36
    at NativeModule.compile (internal/bootstrap/loaders.js:300:5)
```

**Comment by anmonteiro** [comment]
I made a mistake in the 1.10 release. I've marked it as deprecated on npm. fixing.
