### ISSUE TITLE
1.10.1 Installation fails on Windows

### ISSUE THREAD

**Issue by Driphter** [anmonteiro/lumo#471]
```
Error: Not Found https://github.com/anmonteiro/lumo/releases/download/1.10.1/lumo_win64.exe.gz
    at C:\Users\mmyers\AppData\Local\npm\node_modules\lumo-cljs\download\dist\download.js:7:21046
    at u (C:\Users\mmyers\AppData\Local\npm\node_modules\lumo-cljs\download\dist\download.js:1:25024)
    at Generator._invoke (C:\Users\mmyers\AppData\Local\npm\node_modules\lumo-cljs\download\dist\download.js:1:24812)
    at Generator.e.(anonymous function) [as next] (C:\Users\mmyers\AppData\Local\npm\node_modules\lumo-cljs\download\dist\download.js:1:25446)
    at r (C:\Users\mmyers\AppData\Local\npm\node_modules\lumo-cljs\download\dist\download.js:1:1267)
    at a (C:\Users\mmyers\AppData\Local\npm\node_modules\lumo-cljs\download\dist\download.js:1:1477)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by anmonteiro** [comment]
I didn't publish a Windows binary for this release because the CI was running out of heap space. Would you like to built it yourself?

**Comment by anmonteiro** [comment]
I just published the windows release.
