### ISSUE TITLE
Yarn error when building on Debian Buster x86 (32-bit)

### ISSUE THREAD

**Issue by cellularmitosis** [anmonteiro/lumo#497]
Hello,

I recently found out that node.js is available on x86 as an unofficial build, and I thought I'd try building lumo for x86.

See my build scripts at https://gist.github.com/cellularmitosis/bd78de2c76b1f9ac78ccb7216686ae62

It fails with `Error: A package is trying to access another package without the second one being listed as a dependency of the first one`

Full error output:

```
Applying optimizations :simple to 83 sources
Optimizing with Google Closure Compiler, elapsed time: 249543.880541 msecs
Optimizing 83 sources, elapsed time: 254342.856943 msecs
Sifting output files...
Retrieving transit-clj-0.8.309.jar from https://repo1.maven.org/maven2/ (14k)
Retrieving tools.reader-1.3.0.jar from https://repo1.maven.org/maven2/ (51k)
Retrieving transit-java-0.8.332.jar from https://repo1.maven.org/maven2/ (102k)
Sifting output files...
Sifting output files...
Sifting output files...
Sifting output files...
Writing target dir(s)...
/root/tmp/lumo-1.10.1/.pnp.js:25074
    throw firstError;
    ^

Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: babel-helper-evaluate-path (via "babel-helper-evaluate-path")
Required by: babel-plugin-minify-guarded-expressions@npm:0.4.3 (via /root/tmp/lumo-1.10.1/.yarn/cache/babel-plugin-minify-guarded-expressions-npm-0.4.3-24cf10be96-1.zip/node_modules/babel-plugin-minify-guarded-expressions/lib/)

Require stack:
- /root/tmp/lumo-1.10.1/.yarn/cache/babel-plugin-minify-guarded-expressions-npm-0.4.3-24cf10be96-1.zip/node_modules/babel-plugin-minify-guarded-expressions/lib/index.js
- /root/tmp/lumo-1.10.1/.yarn/cache/babel-preset-minify-npm-0.5.0-1e9dc8ba49-1.zip/node_modules/babel-preset-minify/lib/index.js
- /root/tmp/lumo-1.10.1/.yarn/$$virtual/rollup-plugin-babel-minify-virtual-c078fdd82a/0/cache/rollup-plugin-babel-minify-npm-8.0.0-b9abb35954-1.zip/node_modules/rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify.js
- /root/tmp/lumo-1.10.1/scripts/bundle.js
    at Object.makeError (/root/tmp/lumo-1.10.1/.pnp.js:16819:24)
    at resolveToUnqualified (/root/tmp/lumo-1.10.1/.pnp.js:25682:35)
    at resolveRequest (/root/tmp/lumo-1.10.1/.pnp.js:25759:27)
    at Object.resolveRequest (/root/tmp/lumo-1.10.1/.pnp.js:25827:26)
    at Function.module_1.Module._resolveFilename (/root/tmp/lumo-1.10.1/.pnp.js:25057:34)
    at Function.module_1.Module._load (/root/tmp/lumo-1.10.1/.pnp.js:24942:40)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/tmp/lumo-1.10.1/.yarn/cache/babel-plugin-minify-guarded-expressions-npm-0.4.3-24cf10be96-1.zip/node_modules/babel-plugin-minify-guarded-expressions/lib/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30) {
  code: 'MODULE_NOT_FOUND',
  pnpCode: 'UNDECLARED_DEPENDENCY',
  data: {
    request: 'babel-helper-evaluate-path',
    issuer: '/root/tmp/lumo-1.10.1/.yarn/cache/babel-plugin-minify-guarded-expressions-npm-0.4.3-24cf10be96-1.zip/node_modules/babel-plugin-minify-guarded-expressions/lib/',
    issuerLocator: {
      name: 'babel-plugin-minify-guarded-expressions',
      reference: 'npm:0.4.3'
    },
    dependencyName: 'babel-helper-evaluate-path',
    candidates: [
      'babel-plugin-minify-guarded-expressions',
      'babel-helper-flip-expressions'
    ]
  },
  requireStack: [
    '/root/tmp/lumo-1.10.1/.yarn/cache/babel-plugin-minify-guarded-expressions-npm-0.4.3-24cf10be96-1.zip/node_modules/babel-plugin-minify-guarded-expressions/lib/index.js',
    '/root/tmp/lumo-1.10.1/.yarn/cache/babel-preset-minify-npm-0.5.0-1e9dc8ba49-1.zip/node_modules/babel-preset-minify/lib/index.js',
    '/root/tmp/lumo-1.10.1/.yarn/$$virtual/rollup-plugin-babel-minify-virtual-c078fdd82a/0/cache/rollup-plugin-babel-minify-npm-8.0.0-b9abb35954-1.zip/node_modules/rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify.js',
    '/root/tmp/lumo-1.10.1/scripts/bundle.js'
  ]
}

Error attempting to play sound file: Cannot create AudioDevice

                                java.lang.Thread.run              Thread.java:  834
  java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  628
   java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1128
                 java.util.concurrent.FutureTask.run          FutureTask.java:  264
                                                 ...                               
                 clojure.core/binding-conveyor-fn/fn                 core.clj: 2030
                                   boot.core/boot/fn                 core.clj: 1032
                                 boot.core/run-tasks                 core.clj: 1022
                      boot.task.built-in/fn/fn/fn/fn             built_in.clj:  245
boot.user$eval1080$fn__1081$fn__1088$fn__1089.invoke                         :   77
                   adzerk.boot-cljs/eval359/fn/fn/fn            boot_cljs.clj:  169
                   adzerk.boot-cljs/eval416/fn/fn/fn            boot_cljs.clj:  250
                      boot.task.built-in/fn/fn/fn/fn             built_in.clj:  636 (repeats 4 times)
boot.user$eval1163$fn__1164$fn__1171$fn__1172.invoke                         :  105
boot.user$eval1206$fn__1207$fn__1214$fn__1215.invoke                         :  121
                      boot.task.built-in/fn/fn/fn/fn             built_in.clj:  636
                      boot.task.built-in/fn/fn/fn/fn             built_in.clj:  394
boot.user$eval1119$fn__1120$fn__1127$fn__1128.invoke                         :   91
                                  clojure.core/apply                 core.clj:  665
                                                 ...                               
                                      boot.util/dosh                 util.clj:  478
       java.lang.Exception: yarn: non-zero exit status (1)
clojure.lang.ExceptionInfo: yarn: non-zero exit status (1)
    line: 238
```

Anyway, I thought perhaps you've already encountered this issue on x86_64 and know of a solution.

Thanks!

**Comment by cellularmitosis** [comment]
Perhaps this worked prior to Yarn 2.0?  https://github.com/yarnpkg/berry/issues/494
