### ISSUE TITLE
Failure to compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by Rovanion** [anmonteiro/lumo#5]
Following the instructions given in the README I installed boot and subsequently yarn to run `boot dev` on a cloned version of your master branch here on github. But I ended up with the following error:

```
Applying optimizations :simple to 259 sources
nov 10, 2016 11:06:05 FM com.google.javascript.jscomp.LoggerErrorManager println
VARNING: file:/home/rovanion/.m2/repository/org/clojure/google-closure-library/0.0-20160609-f42b4a24/google-closure-library-0.0-20160609-f42b4a24.jar!/goog/format/htmlprettyprinter.js:135: WARNING - Found duplicate value 'BR' in set
goog.format.HtmlPrettyPrinter.BREAKS_FLOW_TAGS_ = goog.object.createSet(
                                                  ^

nov 10, 2016 11:06:05 FM com.google.javascript.jscomp.LoggerErrorManager printSummary
VARNING: 0 error(s), 1 warning(s)
Optimizing with Google Closure Compiler, elapsed time: 24555.474424 msecs
Optimizing 259 sources, elapsed time: 25260.562676 msecs
Sifting output files...
Sifting output files...
Sifting output files...
Sifting output files...
Writing target dir(s)...
/home/rovanion/source/clj/lumo/scripts/build.js:13
  let pos = 0;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
java.lang.Exception: node: non-zero exit status (1)
                      boot.util/dosh                          util.clj:  403
                                 ...                                        
          boot.user/eval885/fn/fn/fn  boot.user5715467476412782232.clj:   23
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  303
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  493
          boot.user/eval970/fn/fn/fn  boot.user5715467476412782232.clj:   29
          boot.user/eval927/fn/fn/fn  boot.user5715467476412782232.clj:   27
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  493
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  493
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  493
   adzerk.boot-cljs/eval311/fn/fn/fn                     boot_cljs.clj:  208
   adzerk.boot-cljs/eval257/fn/fn/fn                     boot_cljs.clj:  135
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  167
boot.task.built-in/fn/fn/fn/fn/fn/fn                      built_in.clj:  348
   boot.task.built-in/fn/fn/fn/fn/fn                      built_in.clj:  348
      boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  345
          boot.user/eval845/fn/fn/fn  boot.user5715467476412782232.clj:   21
                 boot.core/run-tasks                          core.clj:  938
                   boot.core/boot/fn                          core.clj:  948
 clojure.core/binding-conveyor-fn/fn                          core.clj: 2020
                                 ...                                        
Elapsed time: 68,781 sec
```

**Comment by anmonteiro** [comment]
This seems like a problem with your Node.js version.
You can also tweak the `scripts/build.js` script and change `let`s to `var`s.
Also, to build an executable you should run `boot release`, I just realized it's a mistake in the readme

**Comment by Rovanion** [comment]
My installed version of NodeJS is v4.2.6.

**Comment by anmonteiro** [comment]
Yes, that is a little old. Try v6 or v7 and let me know if it fixes the problem for you.

**Comment by Rovanion** [comment]
So after much compiling the build completed and I ventured to run the new binary, but alas it was not to be:

```
┌[rovanion][ThinkT420s][master]:~/source/clj/lumo 
└$ build/lumo 
Lumo 1.0-alpha
ClojureScript 1.9.293
 Exit: Control+D or :cljs/quit or exit
cljs.user=> [eval]:5
e.pending_buf[e.l_buf+e.last_lit]=255&n,e.last_lit++,0===t?e.dyn_ltree[2*n]++:(e.matches++,t--,e.dyn_ltree[2*(be[n]+G+1)]++,e.dyn_dtree[2*h(t)]++),e.last_lit===e.lit_bufsize-1}var U=e("../utils/common"),P=4,M=0,Z=1,H=2,W=0,K=1,X=2,Y=3,V=258,q=29,G=256,$=G+1+q,J=30,Q=19,ee=2*$+1,te=15,ne=16,re=7,ie=256,oe=16,ae=17,se=18,le=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],ue=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],fe=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,7],de=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],ce=512,he=new Array(2*($+2));f(he);var pe=new Array(2*J);f(pe);var me=new Array(ce);f(me);var be=new Array(V-Y+1);f(be);var _e=new Array(q);f(_e);var ge=new Array(J);f(ge);var we,ve,ye,ke=!1;n._tr_init=T,n._tr_stored_block=D,n._tr_flush_block=N,n._tr_tally=F,n._tr_align=L}).call(this,"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{},e("buffer").Buffer,"/home/rovanion/source/clj/lumo/node_modules/pako/lib/zl

TypeError: Cannot read property 'size' of undefined
    at [eval]:5:12876
    at FSReqWrap.oncomplete (fs.js:111:15)
```

**Comment by anmonteiro** [comment]
This is weird. Both my Linux VM and the CI are running Ubuntu 16 and I don't see any problems.

Can you ensure you're on a fresh clone and try again? Thanks!

**Comment by anmonteiro** [comment]
@Rovanion is this still an issue?

**Comment by Rovanion** [comment]
Haven't had time to look at it, and since it took literally two hours to compile lumo I'm not sure that I'll find time in the soon future. So I might as well close this.
